<?PHP
$lang[0]='Bo-Blog Installer';
$lang[1]='Error';
$lang[2]='PHP version is too low to run this program.';
$lang[3]='Conditions and Terms';
$lang[4]='I Agree';
$lang[5]='I Disagree';
$lang[6]='Installation Cancelled';
$lang[7]='You have to agree the terms to install this program.';
$lang[8]='Database Info';
$lang[9]='MySQL Host: ';
$lang[10]='MySQL Username: ';
$lang[11]='MySQL Password: ';
$lang[12]='Database Name:';
$lang[13]='Note: You need to set up a database beforehand.';
$lang[14]='Database Prefix:';
$lang[15]='Can be any string. Better to have an underline at the end.';
$lang[16]='Charset and Collation:';
$lang[17]='What\'s this?';
$lang[18]='Default';
$lang[19]='Forced UTF-8';
$lang[20]='Incorrect setting of charset will cause scrambled codes. <ul><li>If your MySQL version is lower than 4.1.0, please check \'Default\'; </li><li>If your MySQL version is higher than 4.1.0 and default charset is not UTF-8, please check \'Forced UTF-8\';</li><li>If your MySQL version is higher than 4.1.0 and default charset is UTF-8, please check \'Default\';</li><li>If you are not sure, please consult your server administrator.</li></ul>';
$lang[21]='Next';
$lang[22]='Reset';
$lang[23]='Can not establish connection to the database server. Please check your MySQL host, username, password and database name.';
$lang[24]='MySQL version is too low. ';
$lang[25]='Basic Blog Setting';
$lang[26]='Admin Username:';
$lang[27]='Admin Password:';
$lang[28]='Blog Name:';
$lang[29]='Blog Description:';
$lang[30]='Hello, world!';
$lang[31]='Welcome to [acronym=A single user blog engine powered by PHP and MySQL]Bo-Blog[/acronym].';
$lang[32]='Default';
$lang[33]='Default category';
$lang[34]='Default Group';
$lang[35]='Link to homepage';
$lang[36]='Link to RSS feed';
$lang[37]='Link to login/logout';
$lang[38]='Link to profile';
$lang[39]='Link to tag list';
$lang[40]='Link to guestbook';
$lang[41]='Toggle the sidebar';
$lang[42]='View all starred entries';
$lang[43]='Category list';
$lang[44]='Calendar';
$lang[45]='Statistic data';
$lang[46]='Recent entries';
$lang[47]='Recent comments';
$lang[48]='Link groups and links';
$lang[49]='Archives';
$lang[50]='Misc and syndications';
$lang[51]='Copyright';
$lang[52]='China MII ICP License';
$lang[53]='Sidebar announcement';
$lang[54]='Link to view all the links';
$lang[55]='Sidebar search box';
$lang[56]='Installing';
$lang[57]='Congratulations! All necessary tables have been created.';
$lang[58]='Click the button below to continue.';
$lang[59]='Announcement';
$lang[60]='A test announcement.';
$lang[61]='Installation Completed';
$lang[62]='Congratulations! You have successfully installed the program.';
$lang[63]='Click the button below to enter your blog. You may need to delete install/install.php before that.';
$lang[64]='Go to Homepage';
$lang[65]='When tables already exist...';
$lang[66]='Overwrite them and continue';
$lang[67]='Don\'t overwrite then and quit';
$lang[68]='Warning: This will overwrite all existed tables which may already contain some data .';
$lang[69]='View history';
$lang[70]='Dir data/ is not writable. If you are running on a Unix/Linux server, you need to set the property of this directory to 777. If on windows, give the dir an Everyone control permission.';
$lang[71]='Powerful forum system';
$lang[72]='What are you going to do?';
$lang[73]='Install Bo-Blog';
$lang[74]='Repair';
$lang[75]='Please wait...';
$lang[76]='Now Repairing';
$lang[77]='All tables have been fixed.';
$lang[78]='Repair Finished';
$lang[79]='Repair request is finished. You need to set the blog configuration and preferences again in the admin center.';
$lang[80]='Repeat Password:';
$lang[81]='Passwords are empty, or differentiate with each other!';
$lang[82]='Blog Path:';
$lang[83]='Enter the absolute path of your blog.';
$lang[84]='Link to archive list';
$lang[85]='This separates Sidebar One and Sidebar Two.';


$langcopy=array (
0=>'Default Group',
1=>'Powerful forum system',
2=>'Guest',
3=>'User',
4=>'Admin',
5=>'Writer',
6=>'',
7=>'',
8=>'Unknown',
9=>'Sunny',
10=>'Overcast',
11=>'Cloudy',
12=>'Rainy',
13=>'Thundershower',
14=>'Night',
15=>'Snowy'
);
