<?PHP
$lang[0]='Trình cài đặt Bo-Blog';
$lang[1]='Có lỗi';
$lang[2]='Bản PHP quá thấp, không cài đặt được.';
$lang[3]='Đọc thỏa thuận sử dụng';
$lang[4]='Đồng ý';
$lang[5]='Không đồng ý';
$lang[6]='Cài đặt kết thúc';
$lang[7]='Bạn phải đồng ý với thỏa thuận sử dụng mới cài đặt tiếp được.';
$lang[8]='Thiết lập CSDL';
$lang[9]='Địa chỉ MySQL：';
$lang[10]='Tên người dùng MySQL：';
$lang[11]='Mật khẩu MySQL：';
$lang[12]='Tên CSDL MySQL：';
$lang[13]='Chú ý: chương trình không tự động tạo CSDL, vì vậy cần tạo trước 1 CSDL, hoặc dùng CSDL chỉ định của máy chủ';
$lang[14]='Tiền tố bảng dữ liệu：';
$lang[15]='Điền ký tự tùy ý, kiến nghị nên thêm gạch dưới ở sau ký tự cuối cùng';
$lang[16]='Mã ký tự：';
$lang[17]='Đây là gì?';
$lang[18]='Dùng thiết lập mặc định của máy chủ';
$lang[19]='Ép máy chủ dùng UTF-8 lưu và đọc dữ liệu';
$lang[20]='Thiết lập mã ký tự sai có thể gây loạn mã.<ul><li>Nếu bản MySQL thấp hơn 4.1.0, hãy chọn mục trước；</li><li>Nếu bản MySQL cao hơn 4.1.0, nhưng ký tự mặc định không phải UTF-8, hãy chọn mục sau；</li><li>Nếu bản MySQL cao hơn 4.1.0, và ký tự mặc định là UTF-8, hãy chọn mục trước；</li><li>Nếu bạn không hiểu rõ, hãy hỏi nơi cho thuê máy chủ.</li></ul>';
$lang[21]='Tiếp theo';
$lang[22]='Cấu hình lại';
$lang[23]='Không thể kết nối CSDL, hãy đảm bảo địa chỉ, tên người dùng, mậ tkhẩu và tên CSDL của MySQL là chính xác.';
$lang[24]='Bản MySQL quá thấp, không thể cài đặt tiếp.';
$lang[25]='Thiết lập thông tin blog';
$lang[26]='Tên quản lý：';
$lang[27]='Mật khẩu quản lý：';
$lang[28]='Tên Blog：';
$lang[29]='Mô tả Blog：';
$lang[30]='Bài viết thử';
$lang[31]='Chào bạn, cảm ơn bạn đã sử dụng [acronym=chương trình blog cá nhân dựa trên PHP và MySQL]Bo-Blog[/acronym].<br/><br/>Ở đây chúng tôi giới thiệu một sản phẩm diễn đàn BMForum của Bluview, nó có các kỹ thuật tiên tiến nhất so với các chương trình diễn đàn hiện nay.<br/><a href="http://www.bmforum.com"> [b]Bấm tải về[/b]</a><ul><li> [b]<u>Đứng đầu toàn quốc</u> Phá vỡ phương thức phân loại truyền thống —— Chủ đề dựa theo từ khóa (Tags, từ đánh dấu) [/b]<br/>chỉ cần chỉ định một từ khó khi viết bài, là các bài tự liên kết với nhau!</li><li> [b]Kỹ thuật AJAX tiên tiến, ứng dụng phổ biến vào duyệt và đọc bài[/b]<br/>Lật trang nhanh, trả lời nhanh, tất cả đều thanh thoát.</li><li> [b]<u>Đứng đầu toàn quốc về</u> phương thức đăng ký diễn đàn[/b]<br/>Thành viên có thể nỗ lực mời người khác tham gia!</li><li> [b]Chương trình tiêu chuẩn dựa trên XHTML1.0 + CSS[/b]<br/>Hoàn toàn phù hợp tiêu chuẩn quốc tế W3C, làm giao diện rất đơn giản.</li><li> [b]<u>Đứng đầu toàn quốc về</u> viết bài trực quan, giúp viết bài đơn giản hơn[/b]<br/>Qua cách viết bài trực quan, có thể gửi nội dung tiện lợi và an toàn</li><li> [b]Quản lý mặt sau mạnh, định vị nhanh chóng[/b]<br/>Thông qua menu "Tôi muốn" mà nhanh chóng tìm thấy thứ bạn cần</li><li>[b]Tính năng diễn đàn hiệu quả[/b]<br/>Lực tải của DĐ không tiền khoáng hậu</li><li> [b]<u>Đứng đầu thế giới về</u> tải sắp xếp nhiều tệp tinvà hình ảnh[/b]<br/>Dùng chương trình DĐ BMForum, viết bài dễ như trở bàn tay</li><li> [b]<u>Đứng đầu toàn quốc về</u> mã UTF-8 đa ngôn ngữ[/b]<br/> Giao lưu quốc tế càng chặt chẽ</li><li>[b]Hệ thống kiểm soát nhóm người dùng rất lớn[/b]<br/>Dữ liệu người dùng tự phân quyền theo nhóm người dùng</li></ul><br/>Đây là một bài nhật ký viết mẫu. Bạn có thể xóa đi.';
$lang[32]='Phân loại mặc định';
$lang[33]='Đây là phân loại tự động của chương trình.';
$lang[34]='Nhóm Kết nối mặc định';
$lang[35]='Kết nối trang chủ';
$lang[36]='Kết nối RSS';
$lang[37]='Kết nối đăng nhập/thoát';
$lang[38]='Kết nối sửa thôngtincá nhân';
$lang[39]='Xem kết nối trong danh sách Tags';
$lang[40]='Kết nối Lưu bút';
$lang[41]='Kết nối đóng mở cột hai bên';
$lang[42]='Xem nhật ký đã đánh sao';
$lang[43]='Danh mục phân loại';
$lang[44]='Lịch';
$lang[45]='Thống kê dữ liệu đơn giản';
$lang[46]='Bài viết mới nhất';
$lang[47]='Nhận xét mới nhất';
$lang[48]='Nhóm kết nối và kết nối';
$lang[49]='Hồ sơ';
$lang[50]='Các mục khác';
$lang[51]='Bản quyền chương trình';
$lang[52]='Mã số của trang web Bộ thông tin';
$lang[53]='Cột quảng cáo hai bên';
$lang[54]='Xem tất cả kết nối';
$lang[55]='Khung tìm kiếm bên cạnh';
$lang[56]='Đang cài đặt';
$lang[57]='chúc mừng, chương trình lập xong bảng dữ liệu cần thiết.';
$lang[58]='Bấm nút dưới đây để vào bước tiếp theo';
$lang[59]='Thông báo';
$lang[60]='Một thông báo thử';
$lang[61]='Cài đặt thành công';
$lang[62]='Chúc mừng, cài đặt đã hoàn tất.';
$lang[63]='Bấm nút bên dưới vào blog, trước đó hãy xóa tệp tin: install/install.php. Bạn cũng có thể xóa cả thư mục install.';
$lang[64]='Vào trang chủ';
$lang[65]='Làm gì để xử lý bàng dữ liệu trùng tên?';
$lang[66]='Đè lên và tiếp tục cài đặt';
$lang[67]='Không đè lên và ngừng cài đặt';
$lang[68]='Chú ý: Những bảng dữ liệu này có thể lưu dữ liệu của lần cài đặt trước, sau khi đè lên sẽ mất hết dữ liệu này!';
$lang[69]='Xem, quản lý lịch sử đăng nhập';
$lang[70]='Thư mục data/ không ghi được. Nếu bạn dùng máy chủ Unix/Linux, hãy sửa quyền hạn thư mục này 777. Nếu dùng máy chủ Windows, hãy liên hệ người quản lý, sửa thư mục này thành ai (everyone) cũng viết được.';
$lang[71]='Cho bạn thể nghiệm DĐ mới mẻ';
$lang[72]='Bạn định làm gì?';
$lang[73]='Cài đặt mới Bo-Blog';
$lang[74]='Sửa cài đặt đã có';
$lang[75]='Hãy chờ giây lát...';
$lang[76]='Đang sửa';
$lang[77]='Chương trình sửa đã sửa xong bảng dữ liệu';
$lang[78]='Sửa xong';
$lang[79]='Thao tác sửa dã xong. Bạn phải vào khu quẩn lý cấu hình lại blog và thiết lập tham số.';
$lang[80]='Đổi mật khẩu quản lý：';
$lang[81]='Mật khẩu để trống, hoặc hai lần nhập không khớp. Hãy nhập lại.';
$lang[82]='Vị trí của blog';
$lang[83]='Điền đường dẫn <b>tuyệt đối</b> của trang chủ diễn đàn';
$lang[84]='Kết nối chung hồ sơ';
$lang[85]='Phân tách 1 hay 2 cột.';


$langcopy=array (
0=>'Nhóm kết nối mặc định',
1=>'Cho bạn thể nghiệm DĐ hoàn toàn mới',
2=>'Khách',
3=>'Thành viên dăng ký',
4=>'Quản lý',
5=>'Người viết cùng',
6=>'Ynăm ntháng jngày',
7=>'Ynăm^',
8=>'Không rõ',
9=>'Nắng',
10=>'Râm',
11=>'Nhiều mây',
12=>'Mưa',
13=>'Mưa bão',
14=>'Nửa đêm',
15=>'Tuyết'
);