<?PHP
if (!defined('VALIDADMIN')) die ('Access Denied.');
include("data/config.php");
$config['blogcreatetime']=date("Y-m-d H:i:s", $config['blogcreatetime']);
addpref("sec", "{$lna[500]}");
addpref("t", "blogname|{$lna[501]}");
addpref("t", "blogdesc|{$lna[502]}");
addpref("t", "blogkeywords|{$lna[503]}");
addpref("t", "blogcreatetime|{$lna[504]}|(yyyy-mm-dd HH:mm:ss)");
addpref("t", "blogurl|{$lna[506]}|{$lna[507]}<br>{$lna[952]}");
addpref("t", "bloglogo|{$lna[508]}");
addpref("sec", "{$lna[509]}");
addpref("r", "blogopen|{$lna[510]}|{$lna[511]}|{$lna[512]}");
addpref("ta", "message_off|{$lna[513]}");
addpref("r", "registeron|{$lna[514]}|{$lna[511]}|{$lna[512]}");
addpref("ta", "registeroffmess|{$lna[515]}");
addpref("sec", "{$lna[516]}");
addpref("t", "onlinetime|{$lna[517]}|{$lna[518]}<br>{$lna[519]}");
addpref("sel", "timezone|{$lna[520]}|-12>>(GMT - 12:00 hours) Enitwetok, Kwajalien<<-11>>(GMT - 11:00 hours) Midway Island, Samoa<<-10>>(GMT - 10:00 hours) Hawaii<<-9>>(GMT - 9:00 hours) Alaska<<-8>>(GMT - 8:00 hours) Pacific Time (US &amp; Canada)<<-7>>(GMT - 7:00 hours) Mountain Time (US &amp; Canada)<<-6>>(GMT - 6:00 hours) Central Time (US &amp; Canada), Mexico City<<-5>>(GMT - 5:00 hours) Eastern Time (US &amp; Canada), Bogota, Lima, Quito<<-4>>(GMT - 4:00 hours) Atlantic Time (Canada), Caracas, La Paz<<-3.5>>(GMT - 3:30 hours) Newfoundland<<-3>>(GMT - 3:00 hours) Brazil, Buenos Aires, Georgetown, Falkland Is.<<-2>>(GMT - 2:00 hours) Mid-Atlantic, Ascention Is., St Helena<<-1>>(GMT - 1:00 hours) Azores, Cape Verde Islands<<0>>(GMT) Casablanca, Dublin, Edinburgh, London, Lisbon, Monrovia<<1>>(GMT + 1:00 hours) Berlin, Brussels, Copenhagen, Madrid, Paris, Rome<<2>>(GMT + 2:00 hours) Kaliningrad, South Africa, Warsaw<<3>>(GMT + 3:00 hours) Baghdad, Riyadh, Moscow, Nairobi<<3.5>>(GMT + 3:30 hours) Tehran<<4>>(GMT + 4:00 hours) Adu Dhabi, Baku, Muscat, Tbilisi<<4.5>>(GMT + 4:30 hours) Kabul<<5>>(GMT + 5:00 hours) Ekaterinburg, Islamabad, Karachi, Tashkent<<5.5>>(GMT + 5:30 hours) Bombay, Calcutta, Madras, New Delhi<<6>>(GMT + 6:00 hours) Almaty, Colomba, Dhakra<<7>>(GMT + 7:00 hours) Bangkok, Hanoi, Jakarta<<8>>(GMT + 8:00 hours) Beijing, Hong Kong, Perth, Singapore, Taipei<<9>>(GMT + 9:00 hours) Osaka, Sapporo, Seoul, Tokyo, Yakutsk<<9.5>>(GMT + 9:30 hours) Adelaide, Darwin<<10>>(GMT + 10:00 hours) Melbourne, Papua New Guinea, Sydney, Vladivostok<<11>>(GMT + 11:00 hours) Magadan, New Caledonia, Solomon Islands<<12>>(GMT + 12:00 hours) Auckland, Wellington, Fiji, Marshall Island");
addpref("r", "validation|{$lna[521]}|{$lna[511]}|{$lna[512]}|{$lna[522]}<br>{$lna[1170]}");
addpref("r", "loginvalidation|{$lna[523]}|{$lna[511]}|{$lna[512]}|{$lna[522]}<br>{$lna[1170]}");
addpref("r", "registervalidation|{$lna[1018]}|{$lna[511]}|{$lna[512]}|{$lna[522]}");
addpref("r", "applylinkvalidation|{$lna[1019]}|{$lna[511]}|{$lna[512]}|{$lna[522]}<br>{$lna[1170]}");
addpref("sec", "{$lna[524]}");
addpref("r", "closeajax|{$lna[1096]}|{$lna[511]}|{$lna[512]}|<br>{$lna[1097]}");
addpref("r", "closeadminajax|{$lna[1191]}|{$lna[511]}|{$lna[512]}|<br>{$lna[1192]}");
addpref("r", "gzip|{$lna[525]}|{$lna[511]}|{$lna[512]}|{$lna[526]}");
addpref("t", "updatesrc|{$lna[531]}");
addpref("t", "customized404|{$lna[1187]}|<br>{$lna[1188]}");