<?PHP
$weather['blank']['image']='images/weather/blank.gif';
$weather['blank']['text']='{langcopy8}';
$weather['sunny']['image']='images/weather/sunny.gif';
$weather['sunny']['text']='{langcopy9}';
$weather['overcast']['image']='images/weather/overcast.gif';
$weather['overcast']['text']='{langcopy10}';
$weather['cloudy']['image']='images/weather/cloudy.gif';
$weather['cloudy']['text']='{langcopy11}';
$weather['rainy']['image']='images/weather/rainy.gif';
$weather['rainy']['text']='{langcopy12}';
$weather['thunder']['image']='images/weather/thunder.gif';
$weather['thunder']['text']='{langcopy13}';
$weather['night']['image']='images/weather/night.gif';
$weather['night']['text']='{langcopy14}';
$weather['snowy']['image']='images/weather/snowy.gif';
$weather['snowy']['text']='{langcopy15}';
